# Generated by Django 3.1.3 on 2020-11-11 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20201111_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='text',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
    ]
