# Generated by Django 3.1.3 on 2020-11-11 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20201111_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='text',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
    ]
