# Generated by Django 3.1.3 on 2020-11-12 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_auto_20201111_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='content',
            field=models.TextField(default='100'),
        ),
        migrations.AlterField(
            model_name='book',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
