# Generated by Django 3.1.3 on 2020-11-12 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_auto_20201112_0527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='content',
        ),
    ]
