# Generated by Django 3.1.3 on 2020-11-12 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_remove_book_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='tanaka', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='content',
            field=models.TextField(default='some content'),
        ),
    ]
